name: Deploy to Firebase Hosting

on:
  pull_request:

concurrency:
    group: ${{ github.ref || github.run_id }}
    cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
#          cache: 'npm'

      - shell: bash
        run: npm ci

      - shell: bash
        run: npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ZATSIT_DT_APIGREENSCORE_DEV }}
          expires: 30d
          projectId: ${{ vars.FIREBASE_PROJECT_ID }}
